#!/bin/bash
sudo apt-get install -y alsa-utils
 sudo apt install python3-venv python3-pip
 python3 -m venv venv
 source venv/bin/activate && pip install vosk && sudo apt install portaudio19-dev && pip install pyaudio
#  MODEL https://alphacephei.com/vosk/models