#!/bin/bash
if [ -z "$1" ]; then
    echo "Usage: $0 <directory_name>"
    exit 1
fi
echo "Ищем $1"
SEARCH="$1"
read INT
if [ ! -z "$INT" ]; then
    SEARCH="$INT"
fi
echo "ИЩУ $SEARCH"
# Поиск директорий и вывод информации
for DIR in $(sudo find / -type d -name "$SEARCH" 2>/dev/null | grep -v "/.local/share/Trash/" | grep -v "/.Trash-1000/"); do
    echo ""
    echo "file://$DIR"
done